### ISSUE TITLE
Can't add second DTSU-666

### ISSUE THREAD

**Issue by sloniu82** [lmatula/ha_chint_pm#17]
HI.
Using HA integration with DTSU-666 for some time in combination with USR-DR302 tcp modbus gateway.
And this setup is working fine.
But recently I've installed second DTSU-666 to measure car charger consumption. 

I'm trying to add device in integration with seconnd slave id, integration throwing an error.

<img width="897" alt="Zrzut ekranu 2024-03-3 o 10 25 54" src="https://github.com/lmatula/ha_chint_pm/assets/25097611/88ed5938-f439-49df-8e2d-24a9a8722eb5">
<img width="378" alt="Zrzut ekranu 2024-03-3 o 10 26 13" src="https://github.com/lmatula/ha_chint_pm/assets/25097611/5a3b51b9-ea2c-4a9d-b287-a9469925294a">

Debug logs shows:
2024-03-03 10:26:31.371 DEBUG (MainThread) [custom_components.chint_pm] Finished fetching 172168016_502_1_data_update_coordinator data in 0.497 seconds (success: True)
2024-03-03 10:26:41.096 ERROR (MainThread) [custom_components.chint_pm.config_flow] 'ModbusIOException' object has no attribute 'registers'
Traceback (most recent call last):
  File "/config/custom_components/chint_pm/config_flow.py", line 387, in async_step_setup_network
    info = await validate_network_setup(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chint_pm/config_flow.py", line 145, in validate_network_setup
    decoder = BinaryPayloadDecoder.fromRegisters(rr.registers, byteorder=Endian.BIG)
                                                 ^^^^^^^^^^^^
AttributeError: 'ModbusIOException' object has no attribute 'registers'

The main question, is it possble to use read two slave devices using the same tcp network gateway?

**Comment by lmatula** [comment]
Hi,
Theoretical yes, but i've never tested this setup.
I think this is an un handled communication error because miss register attribute
I will try to reproduce this scenario

**Comment by lmatula** [comment]
Hi
Becouse some times HA is't close connection, and make new. I observed while developing some stucked connection my tcp gateway. I'm allowed 5 connection, and make separated developer connection pool (Elfin EE11)
