### ISSUE TITLE
Chint 666 integration error after update 20203.10.3

### ISSUE THREAD

**Issue by matteo710** [lmatula/ha_chint_pm#9]
After update 2023.10.3 version the chint 666 integration don't work. 
I have this error:
'Logger: homeassistant
Source: custom_components/chint_pm/sensor.py:872
Integration: Chint powermeter DxSU-666-h ([documentation](https://github.com/lmatula/ha_chint_pm), [issues](https://github.com/lmatula/ha_chint_pm/issues))
First occurred: 16:18:21 (13 occurrences)
Last logged: 16:19:21

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/chint_pm/sensor.py", line 872, in _handle_coordinator_update
    value = self.coordinator.device.data[self.entity_description.key]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ua'

Can anyone help me?

Thanks

**Comment by matteo710** [comment]
Thanks @lmatula , the patch works perfectly!
